# Configuracion de Base de Datos
# Las variables de entorno permiten que cada
# desarrollador use su propia contrasena local,
# y Docker use la definida en docker-compose.yml

# DB_HOST: en Docker sera "db" (nombre del servicio)
#          en local sera "localhost"
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:tareas_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuracion de JPA / Hibernate

# "update" crea/actualiza tablas automaticamente segun las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect